# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Android Explained
email: dassem.ultor.studio@gmail.com
tagline: Blog for Android Developers
description: >- # this means to ignore newlines until "baseurl:"
 Android app development articles for beginner and advanced learners.
 Topics covering Security, Material Design, Firebase, Maps, Cloud Connectivity, RxJava, MVM, MVP, Dagger, Storage, MySQL, Realm and more.
baseurl: # the subpath of your site, e.g. /blog
url: https://androidexplained.github.io/
github_username:  androidexplained
google_site_verification: google71393c6b85643b61.html
logo: /presentation/logo.png
social:
  name: Android Explained
  links:
    - https://www.facebook.com/Android-Explained-107038627830699
    - https://www.linkedin.com/company/android-explained/
# Build settings
markdown: kramdown
remote_theme: jeffreytse/jekyll-theme-yat
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
